#!/usr/bin/env node
/**
 * update-holders.mjs — refresh the on-chain holder of every 401jK NFT.
 *
 * The NFTs are Metaplex Core assets (account owner program CoREENx…). A Core
 * asset has no SPL token account; the current holder is stored INSIDE the asset
 * account: byte 0 is the key discriminator (1 = AssetV1) and bytes 1..33 are the
 * owner Pubkey. So we just read the 32 accounts and decode that field — no DAS
 * API and no API key required. All 32 are fetched in a single getMultipleAccounts
 * RPC call.
 *
 * Reads:  data/collection.json  (nfts[].mintAddress)
 * Writes: data/holders.json     (generated — do not hand-edit)
 *
 *   node scripts/update-holders.mjs
 *
 * Optional env:
 *   SOLANA_RPC_URL   override the RPC endpoint (default: public mainnet-beta)
 */
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const RPC = process.env.SOLANA_RPC_URL || "https://api.mainnet-beta.solana.com";
const METAPLEX_CORE = "CoREENxT6tW1HoK8ypY1SxRMZTcVPm7R94rH4PZNhX7d";

// --- base58 (Bitcoin alphabet) decode of account bytes -> base58 encode -------
const B58 = "123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz";
function b58encode(bytes) {
  let n = 0n;
  for (const b of bytes) n = n * 256n + BigInt(b);
  let out = "";
  while (n > 0n) {
    const r = n % 58n;
    n /= 58n;
    out = B58[Number(r)] + out;
  }
  for (const b of bytes) {
    if (b === 0) out = "1" + out;
    else break;
  }
  return out;
}

async function rpc(method, params) {
  const res = await fetch(RPC, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ jsonrpc: "2.0", id: 1, method, params }),
  });
  if (!res.ok) throw new Error(`RPC ${method} HTTP ${res.status}`);
  const json = await res.json();
  if (json.error) throw new Error(`RPC ${method}: ${JSON.stringify(json.error)}`);
  return json.result;
}

async function main() {
  const collection = JSON.parse(
    readFileSync(join(ROOT, "data", "collection.json"), "utf8")
  );
  const nfts = collection.nfts.filter((n) => n.mintAddress);
  const mints = nfts.map((n) => n.mintAddress);

  // One call returns all 32 accounts, in the same order as the input array.
  const result = await rpc("getMultipleAccounts", [
    mints,
    { encoding: "base64" },
  ]);
  const accounts = result.value;

  const holders = {};
  let ok = 0;
  for (let i = 0; i < nfts.length; i++) {
    const nft = nfts[i];
    const acc = accounts[i];
    if (!acc) {
      console.warn(`! ${nft.mintAddress} (${nft.title}): account not found`);
      continue;
    }
    if (acc.owner !== METAPLEX_CORE) {
      console.warn(
        `! ${nft.mintAddress} (${nft.title}): unexpected owner program ${acc.owner}`
      );
      continue;
    }
    const data = Buffer.from(acc.data[0], "base64");
    if (data[0] !== 1) {
      console.warn(
        `! ${nft.mintAddress} (${nft.title}): unexpected key byte ${data[0]}`
      );
      continue;
    }
    const owner = b58encode(data.subarray(1, 33));
    holders[nft.mintAddress] = { id: nft.id, title: nft.title, owner };
    ok++;
  }

  // Only rewrite the file (and bump updatedAt) when ownership actually changed,
  // so the daily CI run doesn't produce a noise commit / redeploy every day.
  const outPath = join(ROOT, "data", "holders.json");
  let previous = null;
  try {
    previous = JSON.parse(readFileSync(outPath, "utf8"));
  } catch {
    /* first run — no existing file */
  }
  const unchanged =
    previous &&
    JSON.stringify(previous.holders) === JSON.stringify(holders) &&
    previous.count === ok;

  if (unchanged) {
    console.log(`No holder changes — left data/holders.json untouched (${ok} holders).`);
    if (ok < nfts.length) process.exitCode = 1;
    return;
  }

  const out = {
    _readme:
      "GENERATED by scripts/update-holders.mjs — do not hand-edit. 'updatedAt' is when ownership last changed (the daily check only rewrites this file when a holder changes). 'owner' is the current on-chain holder of each Metaplex Core asset. Note: when an NFT is listed on a marketplace the owner may be a marketplace/escrow program rather than a personal wallet.",
    updatedAt: new Date().toISOString(),
    rpc: RPC.includes("api.mainnet-beta.solana.com") ? "public-mainnet-beta" : "custom",
    count: ok,
    holders,
  };
  writeFileSync(outPath, JSON.stringify(out, null, 2) + "\n");
  console.log(`Wrote data/holders.json — ${ok}/${nfts.length} holders resolved.`);
  if (ok < nfts.length) process.exitCode = 1;
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
