#!/usr/bin/env node
/**
 * update-trades.mjs — refresh the last SECONDARY SALE of every 401jK NFT.
 *
 * Data source: Magic Eden's public v2 per-token activities endpoint
 *   https://api-mainnet.magiceden.dev/v2/tokens/<mint>/activities
 * No API key required (verified HTTP 200 unauthenticated). Each activity has
 * { type, price (SOL), blockTime (unix s), seller, buyer, signature, ... }.
 *
 * We only count SECONDARY SALES — `buyNow` (bought from a listing) and
 * `acceptBid`. The `mint` event is deliberately ignored: every 401jK NFT was
 * minted into the project's own wallet and sits there until the Magic Eden
 * listing, so a piece that has never been bought correctly reports "no trade".
 *
 * Reads:  data/collection.json  (nfts[].mintAddress)
 * Writes: data/trades.json      (generated — do not hand-edit)
 *
 *   node scripts/update-trades.mjs
 */
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const ME_BASE = "https://api-mainnet.magiceden.dev/v2";
const SALE_TYPES = new Set(["buyNow", "acceptBid"]);
const THROTTLE_MS = 800; // ~1.25 req/s — ME's public limit is strict
const MAX_RETRIES = 4;

const sleep = (ms) => new Promise((r) => setTimeout(r, ms));

async function fetchActivities(mint) {
  const url = `${ME_BASE}/tokens/${mint}/activities?offset=0&limit=20`;
  for (let attempt = 0; ; attempt++) {
    const res = await fetch(url, { headers: { accept: "application/json" } });
    if (res.ok) return res.json();
    // 429 (and transient 5xx) — exponential backoff and retry a few times.
    if ((res.status === 429 || res.status >= 500) && attempt < MAX_RETRIES) {
      await sleep(1200 * 2 ** attempt);
      continue;
    }
    throw new Error(`ME HTTP ${res.status}`);
  }
}

/** Most recent secondary sale from a token's activity list, or null. */
function lastSale(activities) {
  const sales = (activities || [])
    .filter((a) => SALE_TYPES.has(a.type) && typeof a.price === "number" && a.price > 0)
    .sort((a, b) => (b.blockTime || 0) - (a.blockTime || 0));
  const s = sales[0];
  if (!s) return null;
  return {
    priceSol: s.price,
    date: new Date(s.blockTime * 1000).toISOString(),
    signature: s.signature || null,
    marketplace: "magiceden",
  };
}

async function main() {
  const collection = JSON.parse(
    readFileSync(join(ROOT, "data", "collection.json"), "utf8")
  );
  const nfts = collection.nfts.filter((n) => n.mintAddress);

  const outPath = join(ROOT, "data", "trades.json");
  let previous = null;
  try {
    previous = JSON.parse(readFileSync(outPath, "utf8"));
  } catch {
    /* first run — no existing file */
  }
  const prevTrades = previous?.trades || {};

  const trades = {};
  let salesFound = 0;
  let errors = 0;

  for (const nft of nfts) {
    try {
      const sale = lastSale(await fetchActivities(nft.mintAddress));
      if (sale) {
        trades[nft.mintAddress] = { id: nft.id, title: nft.title, ...sale };
        salesFound++;
      }
    } catch (err) {
      // A transient ME hiccup must not erase a sale we already know about —
      // carry the previous value forward and flag for a non-zero exit.
      errors++;
      console.warn(`! ${nft.mintAddress} (${nft.title}): ${err.message}`);
      if (prevTrades[nft.mintAddress]) {
        trades[nft.mintAddress] = prevTrades[nft.mintAddress];
        if (trades[nft.mintAddress].priceSol != null) salesFound++;
      }
    }
    await sleep(THROTTLE_MS);
  }

  // Idempotent / no-noise: only rewrite (and bump updatedAt) when the set of
  // sales actually changed, so the daily CI run doesn't commit every day.
  const unchanged =
    previous && JSON.stringify(previous.trades) === JSON.stringify(trades);
  if (unchanged) {
    console.log(`No trade changes — left data/trades.json untouched (${salesFound} sales).`);
    if (errors) process.exitCode = 1;
    return;
  }

  const out = {
    _readme:
      "GENERATED by scripts/update-trades.mjs — do not hand-edit. Last SECONDARY SALE (Magic Eden buyNow/acceptBid) per mint; NFTs never sold are absent here and render as 'No trades yet'. 'date' is the sale's on-chain block time (ISO); the front-end derives the '3d ago' relative label from it. 'priceSol' is the sale price in SOL. 'updatedAt' only changes when a sale changes.",
    updatedAt: new Date().toISOString(),
    source: "magiceden-v2-activities",
    salesCount: salesFound,
    trades,
  };
  writeFileSync(outPath, JSON.stringify(out, null, 2) + "\n");
  console.log(`Wrote data/trades.json — ${salesFound} sale(s) across ${nfts.length} NFTs.`);
  if (errors) process.exitCode = 1;
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
